package controller

import (
	"net/http"

	"github.com/QuantumNous/new-api/service"
	"github.com/gin-gonic/gin"
)

// GetChannelConcurrencyStatus returns this process' real-time upstream capacity
// counters. Upstream secrets are never included; key dimensions use short,
// irreversible fingerprints generated by the service layer.
func GetChannelConcurrencyStatus(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"success": true,
		"data": gin.H{
			"scope":   "local",
			"warning": "当前仅统计本实例；跨节点严格并发需要共享 Redis 额度组",
			"items":   service.ChannelConcurrencySnapshotList(),
		},
	})
}
